# Generated by Django 2.1.7 on 2020-06-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200624_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='session',
            new_name='ip',
        ),
    ]
