# Generated by Django 2.1.7 on 2020-06-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colecaoerp',
            old_name='user',
            new_name='colecaoB2b',
        ),
    ]
