# Generated by Django 2.1.7 on 2020-06-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0002_auto_20200613_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecaob2b',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
