# Generated by Django 2.1.7 on 2020-06-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0006_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
