# Generated by Django 2.1.7 on 2020-06-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0007_auto_20200618_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='static/banners/'),
        ),
    ]
