# Generated by Django 2.1.7 on 2020-09-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('params', '0009_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='ordem',
        ),
        migrations.AlterField(
            model_name='periodo',
            name='desc_periodo',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='periodo_faturamento',
            field=models.DateField(unique=True),
        ),
    ]
